// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: like.proto

package like

import (
	"context"

	"zhihu/app/like/rpc/like_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IsThumbupRequest  = like_pb.IsThumbupRequest
	IsThumbupResponse = like_pb.IsThumbupResponse
	ThumbupRequest    = like_pb.ThumbupRequest
	ThumbupResponse   = like_pb.ThumbupResponse
	UserThumbup       = like_pb.UserThumbup

	Like interface {
		Thumbup(ctx context.Context, in *ThumbupRequest, opts ...grpc.CallOption) (*ThumbupResponse, error)
		IsThumbup(ctx context.Context, in *IsThumbupRequest, opts ...grpc.CallOption) (*IsThumbupResponse, error)
	}

	defaultLike struct {
		cli zrpc.Client
	}
)

func NewLike(cli zrpc.Client) Like {
	return &defaultLike{
		cli: cli,
	}
}

func (m *defaultLike) Thumbup(ctx context.Context, in *ThumbupRequest, opts ...grpc.CallOption) (*ThumbupResponse, error) {
	client := like_pb.NewLikeClient(m.cli.Conn())
	return client.Thumbup(ctx, in, opts...)
}

func (m *defaultLike) IsThumbup(ctx context.Context, in *IsThumbupRequest, opts ...grpc.CallOption) (*IsThumbupResponse, error) {
	client := like_pb.NewLikeClient(m.cli.Conn())
	return client.IsThumbup(ctx, in, opts...)
}
