// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LoginRequest struct {
	Mobile string `json:"mobile"`
}

type LoginResponse struct {
	UserID int64 `json:"user_id"`
	Token  Token `json:"token"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	UserID int64 `json:"user_id"`
	Token  Token `json:"token"`
}

type Token struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type UserInfoResponse struct {
	UserID   int64  `json:"user_id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}
